### ISSUE TITLE
Incompatible with Orespawn mod

### ISSUE THREAD

**Issue by Stryker5260** [ata4/dragon-mounts#13] opened 2015-02-20 20:03 UTC
Incompatible with Orespawn mod. Root of problem is unknown, game crashes on world load. 
Crash report:
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 2/20/15 11:54 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.network.NetHandlerPlayClient.func_147281_a(NetHandlerPlayClient.java:744)
	at net.minecraft.network.play.server.S0FPacketSpawnMob.func_148833_a(SourceFile:97)
	at net.minecraft.network.play.server.S0FPacketSpawnMob.func_148833_a(SourceFile:15)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2049)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.network.NetHandlerPlayClient.func_147281_a(NetHandlerPlayClient.java:744)
	at net.minecraft.network.play.server.S0FPacketSpawnMob.func_148833_a(SourceFile:97)
	at net.minecraft.network.play.server.S0FPacketSpawnMob.func_148833_a(SourceFile:15)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Stryker5260'/51, l='MpServer', x=-29.47, y=57.62, z=-761.55]]
	Chunk stats: MultiplayerChunkCache: 10, 19
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-190,4,-578), Chunk: (at 2,0,14 in -12,-37; contains blocks -192,0,-592 to -177,255,-577), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
	Level time: 85142 game time, 420017 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 3 total; [EntityItem['item.item.arrow'/52, l='MpServer', x=-24.94, y=56.13, z=-767.03], EntityItem['item.item.bone'/53, l='MpServer', x=-26.28, y=56.13, z=-765.59], EntityClientPlayerMP['Stryker5260'/51, l='MpServer', x=-29.47, y=57.62, z=-761.55]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_31, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 782040200 bytes (745 MB) / 1268252672 bytes (1209 MB) up to 2863661056 bytes (2731 MB)
	Mod Pack: Unknown / None
	LiteLoader Mods: 1 loaded mod(s)
          - VoxelMap version 1.2.3
	LaunchWrapper: 30 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: optifine.OptiFineClassTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: codechicken.lib.asm.ClassHeirachyManager
          - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
          - Transformer: codechicken.core.asm.TweakTransformer
          - Transformer: codechicken.core.asm.DelegatedTransformer
          - Transformer: codechicken.core.asm.DefaultImplementationTransformer
          - Transformer: invtweaks.forge.asm.ContainerTransformer
          - Transformer: codechicken.nei.asm.NEITransformer
          - Transformer: api.player.forge.PlayerAPITransformer
          - Transformer: net.smart.core.SmartCoreTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
          - Transformer: invtweaks.forge.asm.ITAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.thevoxelbox.voxelmap.litemod.VoxelMapTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 Optifine OptiFine_1.7.10_HD_U_B5 33 mods loaded, 33 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1291} [Forge Mod Loader] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1291} [Minecraft Forge] (forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{1.0.4.35} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	NotEnoughItems{1.0.4.83} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.83-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	PlayerAPI{1.1} [Player API] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SmartCore{1.0} [Smart Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ModName{0.1.7} [ModName] (0.1.7 Gun mod by bradleyTGGB) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	tesseract{1.0.3} [Tesseract Mod] (1.7.10-tesseract-1.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	securitycraft{v1.7.1} [SecurityCraft] ([1.7.10] SecurityCraft 1.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DamageIndicatorsMod{3.2.3} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	betterrecords{1.7.10-1.1.9} [Better Records] (betterrecords-1.7.10-1.1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiblioCraft{1.9.2} [BiblioCraft] (BiblioCraft[v1.9.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ChickenChunks{1.3.4.17} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.17-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	props{1.11} [Decocraft] (Decocraft-v1.11_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	jawser{1.0.0} [Decorative Videogame Systems] (Decorative Game Systems mod v1.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Dirtbike{v1.2.0} [Dirtbike Mod] (Dirtbike Mod - v1.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DragonMounts{r41-1.7.10} [Dragon Mounts] (DragonMounts-r41-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	foxlib{1.7.10-0.7.0} [FoxLib] (FoxLib-1.7.10-0.7.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	grim3212core{V0.2 - 1.7.10} [Grim3212 Core] (Grim3212 Core-V0.2 - 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	moreplayermodels{1.7.10b} [MorePlayerModels] (MorePlayerModels_1.7.10b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	cfm{3.4.7} [§9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OreSpawn{1.7.10.20.2} [OreSpawn] (orespawn-1.7.10-20.2) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	parachutemod{1.7.10} [Parachute Mod] (parachutemod-1.7.10-2.5.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	pokeball{V0.1 - 1.7.10} [Pokeball] (Pokeball-V0.1 - 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	examplemod{1.0} [Example Mod] (S3DGM-1.7.10-0.6.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Stefinus Jetpacks{0.6.3} [Stefinus Jetpacks] (S3DGM-1.7.10-0.6.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	S3DGM{0.6.3} [Stefinus 3D Gun Mod] (S3DGM-1.7.10-0.6.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SmartMoving{15.2} [Smart Moving] (SmartMoving-1.7.10-15.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SmartRender{2.0} [Smart Render] (SmartRender-1.7.10-2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Tails{1.7.10-1.3.0} [Tails] (Tails-1.7.10-1.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	toolsdoneright{1.1.4} [Tools Done Right] (Tools Done Right by NukeDuck [1.7.10][1.1.4] (1)) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Launched Version: 1.7.10-Forge10.13.2.1291
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 8470D GL version 4.2.12420 Compatibility Profile Context 13.151.0.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by jredfox** [comment] 2015-12-23 19:17
I have this in my modpack with orespawn try updating your forge and see if it fixes it.  I am on 1588 build of 1.7.10

**Comment by DovahStud** [comment] 2016-01-24 06:55
@jredfox Made an account just to say I just updated to this version of forge and every time I right click the egg, it disappears, rather than the game crashing. Have you had issues like this? Do you actually have any dragons? Just wondering :/

**Comment by jredfox** [comment] 2016-01-24 19:52
I havn't tested it again yet but, I will do that now.

**Comment by jredfox** [comment] 2016-01-24 22:13
CONFIRMED. DOESN'T WORK WITH THE ORESPAWN MOD PLEASE FIX THIS!

**Comment by DovahStud** [comment] 2016-01-25 00:12
@jredfox Easy with the caps rage man. I've known of this bug for a while. I'm pretty sure it's a known incompatibility. I just with someone would figure out how to edit Orespawn's ID's to auto assign rather than them being a fixed range :/

**Comment by jredfox** [comment] 2016-01-26 23:03
no you need to tell the mod maker right now! what's a modpack without orespawn and dragon mounts? it;s not

**Comment by DovahStud** [comment] 2016-01-26 23:40
@jredfox The Orespawn mod author abandoned it to make his own game incorporating the mod into it. He's basically the only one who can make them compatible, because Orespawn's IDs are all static rather than using Forge's auto-assign system. I think we're SOL.

**Comment by Spartan322** [comment] 2016-01-27 01:17
According to what was stated, this is a "can't fix" problem, which is practically a wontfix problem, should be closed if that is the case

**Comment by ata4** [comment] 2016-01-28 22:32
Agreed, I can't put in workarounds for every mod that doesn't follow common conventions to avoid conflicts with other mods. The entity ID of this mod can be configured in the config file, maybe choose a manual one if the automatically assigned ones cause problems.

**Closed** 2016-01-28 22:32 UTC
Labels: bug, wontfix

**Comment by jredfox** [comment] 2016-01-29 02:32
but, this is orespawn and practically no mods for 1.7.10 add in features for the dragon egg at all.  Why don't you overide it.  if the override fails see my other comment on the other issue for your answer to both issues to make a patch for .1.7.10.  Can you fix the bugs you did in 1.8 and 1.8.8 to 1.7.10 please it's a stable version where all the mods are almost all are currently in.

**Comment by Spartan322** [comment] 2016-01-29 02:33
This is an issue which can not be fixed, because Orespawn has problems and Forge does not allow this type of modification without killing Minecraft (besides being obfuscated anyway, this is not possible)

**Comment by jredfox** [comment] 2016-01-29 04:55
it can be re-overided are you an expert modder?  I know it can it's just pretty advanced and I don't know how to do that. I am sure atomic stryker and other great/ advanced modders will know how to do this easily except that to avoid him contacting other people I came up with a perfectly logically method of approach.

**Comment by Spartan322** [comment] 2016-01-29 12:43
This was closed for multiple wontfix/cantfix reasons, this means that this issue should not be argued further and actually won't/can't be fixed. I am a developer that knows Forge and this conversation on fixing the issue is useless because it can not be done, orespawn is not open source and can't be fixed, and multiple mods have this problem and most can't solve it due to this very reason, if you have anyone to complain to, complain to the developer of orespawn, who I suppose doesn't care about the mod anymore anyway, so unfortunately, that means there is nothing that can be done.

**Comment by jredfox** [comment] 2016-01-29 21:27
well it can be fixed esaly did you code this mod? then you don't know what is going on. The dragon egg should be able to be able to convert it to a seperate block which will be the same purpose if the dragon egg properties get overided. If you can't sense that it is getting overided then make a config option to use the method I am explaining to you.  You should be able to break it with a pickaxe and then put it in a crafting table then it converts to the modded dragon egg. after that you can do what you normally do.  and the ones spawning in chests should be auto converted to the modded dragon egg.  so in conclustion *you can fix and you will fix**.  if you can't fix this there are plenty of modders out there that can help with this issue. it's not just an issue with this mod it's an issue with any incompatible mods that edits the dragon egg.

**Comment by Spartan322** [comment] 2016-01-29 22:05
I honestly don't care, yes, it actually can be fixed, but the point of the matter is that its not going to, that is why this issue was closed with a wontfix tag. The other thing is orespawn is out dated, and creating exceptions for one specific mod which few people use (due to the fact it is outdated) is horrible practice, its also a horrible excuse to ask for an update for such a small problem, it is unfortunate, but Forge and Dragon Mounts (and especially not Minecraft if you actually look into the cruddy design behind it) was not designed as an end all, be all.

Also I don't need to know the whole system to know what you describe is horrible practice, this is how you devolve as a developer. And even then, I'm pretty sure a majority of users wouldn't recognize this fix. And if this only creates more issues (whether compile or runtime or in style) and doesn't actually help a majority, or nearly a majority of people, then it is not worth doing.

If there is a majority then it could be considered. Otherwise, just stop commenting on this issue, it has already been marked and is not going to be fixed soon if ever.

**Comment by jredfox** [comment] 2016-01-29 22:29
orespawn works on the latest build of forge and is one of the greatest mods ever seen. it's up there with the original aether mod (mc1.2.5) evil minecraft (mc 1.2.5) creeps and weirdos (mc 1.2.5) aoa nevermine 2  and divinerpg mod.  it's not just this being affected look at the elysium mod . if your not the coder then why are you doing this to the mod and the modder and the comunity.

**Comment by Spartan322** [comment] 2016-01-29 23:10
because it has been clearly stated that this isn't being fixed and won't be fixed

**Comment by jredfox** [comment] 2016-02-01 01:05
this isn't an issue with orepsawn it's also an issue with the Elysium.  if he fixes Elysium it will fix this now . that isn't marked with a can't fix now is it. if your not the coder of the mod stop saying what he can and cannot do.

**Comment by Spartan322** [comment] 2016-02-01 02:39
Its a wontfix, he isn't bothering with it. So please stop spaming my notifications, this isn't being bothered with for multiple reasons.

**Comment by lillycutecat8899** [comment] 2016-06-12 00:08
All they really have to do is remove the Dragons from Orespawn, I'm pretty sure that could fix it, if somebody knows how to code it.

**Comment by Mremenar** [comment] 2019-04-24 17:17
I know you don't want to deal with this, but this is something that if you did fix would make you a coding  hero of LEGENDARY status.  Lots of Minecrafters want this; you are among the very few that can actually do it.

**Comment by Mremenar** [comment] 2019-11-19 03:42
I am learning Java right now, so I apologize in advance for any noobness in this question:
You stated "I just wish someone would figure out how to edit Orespawn's ID's to auto assign rather than them being a fixed range" -- what would be the proper Java code to ensure that IDs auto assigned?
Thank you in advance for your response.

**Comment by Mremenar** [comment] 2019-12-01 02:00
As per your code/notes in your DragonMountsConfig.class:

"this.dragonEntityID = config.getInt("dragonEntityID", "server", this.dragonEntityID, -1, 255, "Overrides the entity ID for dragons to fix problems with manual IDs from other mods.\nSet to -1 for automatic assignment (recommended).\nWarning: wrong values may cause crashes and loss of data!");"

FYI, Orespawn has 935 entries with fixed IDs.  Changing them from fixed IDs to "-1" does result in an orespawn.jar that is still functional and playable in Minecraft, even with many other mods--but not Dragon Mounts.  The dragons are still invisible, but can be heard.

Changing the values in Orespawn to "-1, 255" or "-1, 255," result in multiple errors and a refusal by javac to compile.

I'm inclined to believe based on recoding Orespawn per your specifications and recompiling that the issue is NOT the static IDs, but that there is some other issue with Dragon Mounts, being that Dragon Mounts will not function properly with the recoded Orespawn.  

I guess it's a moot point since you've abandoned this mod, Danger has abandoned Orespawn, forge modding won't support 1.7.10 and Orespawn won't compile in 1.8.ANYTHING since Danger's style was to use public static ints for EVERYTHING when he should've been using Booleans, enums, interfaces and  classes.  <sigh>
